### ISSUE TITLE
FileZilla on MacOS

### ISSUE THREAD

**Issue by ohan16** [sumeetpalsingh/NGS_Course#2]
Hello,

I can connect to galaxy with FileZilla (and upload my data) from home but not from the Lab. I believe there is a firewall or something like that preventing FileZilla to connect to usegalaxy.org from our lab network..

Do you know what can I do do go around?

**Comment by sumeetpalsingh** [comment]
Hello Ohan16,

Unfortunately in this case, the best people to help you out would be the IT Department from your university. I am sure they can help you configure the FTP client correctly. Without knowing details about your lab's network, it is difficult to provide a viable solution. 

Hope you get it working.

**Comment by sumeetpalsingh** [comment]
A go-around would be to upload without using FTP, but it may take longer and the connection may timeout. But it could work for a few files / upload one file at a time.

**Comment by ohan16** [comment]
Hello I sumeet,

I actually am working with exomic data so, it's pretty big. I
unsuccessfully tried to upload them directly for 3 weeks, so the FTP looks
perfect for me!
I am able to upload with FileZilla from my home so it's cool ;-)

Olivier

Le dim. 7 juin 2020 à 21:24, Sumeet Pal Singh <notifications@github.com> a
écrit :

**Comment by sumeetpalsingh** [comment]
One option / investment that might be useful for you would be install Galaxy locally (on your computer). Details are here: https://galaxyproject.org/admin/get-galaxy/
Thus, you won't be troubled by data transfer, as there will be none.
 
You will, however, need Linux / Mac and need to install the tools that Galaxy calls to (like Trim Galore!, hisat2, htseq-count). You should use bioconda for these.

I run Galaxy on my laptop with 8 Gb RAM and 500 Gb free hard-drive space. Runs perfectly. After finishing a analysis, I save the history on an external hard-drive and purge the data.
